
kind: Deployment
apiVersion: apps/v1
metadata:
  name: participatory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: participatory
  template:
    metadata:
      labels:
        app: participatory
    spec:
      containers:
      - name: participatory
        image: gcr.io/PROJECT_ID/IMAGE:TAG
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
        imagePullPolicy: Always
        ports:
        - name: participatory
          containerPort: 3001