
apiVersion: v1
kind: Service
metadata:
  name: participatory
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: participatory
  type: LoadBalancer
